# APP CONFIG

[need1]
symbols = ["BTCUSDT", "ETHUSDT", "DOGEUSDT"]

[need2]
    [need2.symbol1]
    symbol='ETHUSDT'
    critical_price=1111.74
    volume=400    # 成交量
    # [need2.symbol2]
    # symbols='BTCUSDT'
    # critical_price=1111.75
    # volume=400 